name: Version and Deploy

on:
  push:
    branches: ["main"]

  # Erlaubt das manuelle Starten über GitHub
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # JOB 1: Auto-Versionierung
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'add,refs,feat'
          major-wording: 'MAJOR,cut'
          patch-wording: 'fix,patch'
          rc-wording: 'RELEASE,alpha'

  # JOB 2: Deployment zu GitHub Pages (Startet ERST nach der Versionierung)
  deploy:
    needs: bump-version
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
